apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-webapp
  name: go-webapp
  namespace: _{_NAMESPACE_}_
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: go-webapp
  type: NodePort