name: first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        
        - name: List and Read file
          run: |
            echo "My first Github Actions Job"
            ls -ltra
            cat README.md

        - name: Generat ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a Dragon........RAWR" >> dragon.txt

        #  - name: List files
        #  run: ls

        #  - name: Read file
        #  run: cat README.md