name: Variables at different levels

on: 
  push

env:
   CONTAINER_REGISTRY: docker.io
   DOCKER_USERNAME: tundeade
   IMAGE_NAME: tundeade/go-web-app

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: Docker Login
      env:
        DOCKER_PASSWORD: Do@brzes
      run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
    - name: Docker Run
      run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
